import type { VendorBooth } from "../../types/content";

export const vendors: VendorBooth[] = [
  {
    booth: "Booth 1",
    title: "Vintage Jewelry",
    category: "Vintage Finds",
    description: "Collected statement pieces, delicate heirloom-inspired accents, and timeless vintage sparkle.",
    image: "/images/vendor-booth.svg",
    featured: true,
  },
  {
    booth: "Booth 2",
    title: "Handmade Candles",
    category: "Handcrafted Goods",
    description: "Small-batch candles with layered scent stories, warm vessels, and boutique presentation.",
    image: "/images/handmade-display.svg",
    featured: true,
  },
  {
    booth: "Booth 3",
    title: "Antique Furniture",
    category: "Home Decor",
    description: "Character-rich pieces, painted finishes, and vintage furnishings selected for style and story.",
    image: "/images/antique-vignette.svg",
  },
  {
    booth: "Booth 4",
    title: "Retro Toys",
    category: "Collectibles",
    description: "Nostalgic pieces, playful finds, and collectible objects displayed with a curated touch.",
    image: "/images/vendor-booth.svg",
  },
  {
    booth: "Booth 5",
    title: "Boutique Home Accents",
    category: "Home Decor",
    description: "Layered pillows, vessels, artwork, and styling pieces for collected interior looks.",
    image: "/images/market-interior.svg",
  },
  {
    booth: "Booth 6",
    title: "Southern Linen Co.",
    category: "Boutique Gifts",
    description: "Textiles, host gifts, and soft goods that feel elevated, giftable, and locally sourced.",
    image: "/images/handmade-display.svg",
  },
  {
    booth: "Booth 7",
    title: "Hand-Poured Soaps",
    category: "Handcrafted Goods",
    description: "Artisan body care, soaps, and small wellness goods with boutique shelf presence.",
    image: "/images/handmade-display.svg",
  },
  {
    booth: "Booth 8",
    title: "Painted Cottage Pieces",
    category: "Vintage Finds",
    description: "Refinished furniture, cottage-painted accents, and collected charm for the home.",
    image: "/images/antique-vignette.svg",
  },
  {
    booth: "Booth 9",
    title: "Vinyl & Retro Audio",
    category: "Collectibles",
    description: "Records, retro listening accessories, and music memorabilia with a nostalgic point of view.",
    image: "/images/vendor-booth.svg",
  },
  {
    booth: "Booth 10",
    title: "Seasonal Porch Decor",
    category: "Seasonal Decor",
    description: "Rotating porch styling, wreaths, layered seasonal decor, and event-driven display goods.",
    image: "/images/market-fall.svg",
  },
  {
    booth: "Booth 11",
    title: "Heritage Collectibles",
    category: "Collectibles",
    description: "Curiosities, keepsakes, and collected display pieces that reward slow browsing.",
    image: "/images/antique-vignette.svg",
  },
  {
    booth: "Booth 12",
    title: "Artisan Paper Goods",
    category: "Boutique Gifts",
    description: "Stationery, hand-illustrated cards, journals, and gift-ready paper products.",
    image: "/images/handmade-display.svg",
  },
];
